name: flutter_summary
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  bloc: ^6.1.0
  flutter_bloc: ^6.1.0
  pull_to_refresh: ^1.6.3
  # fluttertoast: ^5.0.1
  oktoast: ^2.3.2
  dio: ^3.0.9
  crypto: ^2.1.4
  #moor数据库相关
  # moor: ^3.4.0
  # sqlite3_flutter_libs: ^0.2.0
  # path_provider: ^1.6.24
  # provider: ^4.3.0
  list_data_cache_manager: ^0.0.1
  #获取包信息
  package_info: ^0.4.0+14
  shared_preferences: ^0.5.3+1
  # cached_network_image: ^2.0.0
  # flutter_qr_reader: ^1.0.3
  #mqtt
  mqtt_client: ^5.6.3
  #极光分享
  #支持sliver的排序控件
  reorderables: ^0.3.2
  #闪烁效果控件
  shimmer: ^1.1.1
  #获取设备信息
  device_info: ^0.4.2+4
  #虚线边框
  dotted_border: ^1.0.5
  # app跳转
  url_launcher: ^5.4.5
  # jshare_flutter_plugin: ^1.0.2
  permission_handler:
    path: ./local_packages/permission_handler-5.0.1+1/
  # jpush_flutter:
  #   path: ./local_packages/jpush_flutter-0.5.5/
  flutter_mobile_imsdk: ^0.0.2
  #AVL树和红黑树
  dart_tree: ^0.0.3
  #跨平台开发框架
  # flutter_boost: ^1.17.1
  list_index_manager: ^0.0.1
  image: ^2.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^1.10.4
  #flutter packages pub run build_runner build
  #flutter packages pub run build_runner watch
  #配合moor数据库使用
  # moor_generator: ^3.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/files/china_region/
# assets-generator-begin
# assets/images/*
    - assets/images/icon/
# assets-generator-end

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
